"""Add description column  to Product

Revision ID: 0441b043b8b5
Revises: b19e2231b491
Create Date: 2023-12-01 10:57:15.492470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0441b043b8b5'
down_revision = 'b19e2231b491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripiton', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('descripiton')

    # ### end Alembic commands ###
